services:
  flux-server:
    build: .
    user: "0:0"
    ports:
      - "8080:8080"
    volumes:
      - /mnt/hf-cache-disk:/mnt/hf-cache
      - outputs:/mnt/outputs
      - ./loras:/app/loras
      - ./models:/app/models
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    env_file:
      - .env
    shm_size: '2g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  outputs:
